### PR TITLE
add aransafp to the list intern

### PR DESCRIPTION
**Pull request by aransafp**
Preview URL is https://raw.githack.com/aransafp/open-source/feature/aransafp/index.html

### CODE REVIEW

**Comment by empeje** [comment]
Thank you for your first PR. I'll put this on hold until every step is finished.

You can check your completion status in here https://open-source.kulkul.tech/en_ID/#!pages/progress.md

---

Side notes:
- I observed a lot of aspiring interns stop in here thinking that it is the only need they need to do to be accepted as an intern which is WRONG.
- Maybe we need to move this step to the very last of the step.
- If you want @aransafp you can can help me create an issue ticket for this problem and create another PR for this.

**Comment by empeje** [comment]
Hi @aransafp please change the date to monday next week and we will merge the PR ya as discussed on the phone.

**Comment by aransafp** [comment]
Hi @empeje I already update it, please review it. thank you

**Comment by empeje** [comment]
Good job, welcome to KulKids!

**Pull request merged**
