### PR TITLE
add ashok to the list of interns

### PR DESCRIPTION
**Pull request by 3Shoka**
here is the preview [URL](https://rawcdn.githack.com/3Shoka/open-source/feature/add-ashook/en_ID/#!index.md)

### CODE REVIEW

**Review by empeje — COMMENTED** [review]
The PR looks good, just need to finish the first steps before moving forward.

**Comment by 3Shoka** [comment]
I already installed **ngecilin** on my browser, [this is the screenshot](https://i.imgur.com/wYpTbTR.png).
Am I missunderstod the step ?

**Comment by empeje** [comment]
Awesome, you're taking a great step by successfully installed Ngecilin on your computer.

---

> The PR looks good, just need to finish the first steps before moving forward.

For my reply earlier I mean **"first steps"** with s, so you need to finish the entire process, not only the 1st step of the series of steps.

Hope it answers your confusion @3Shoka

**Comment by 3Shoka** [comment]
Ops, sorry for that, and thanks for the clarification

**Comment by empeje** [comment]
Any difficulty on completing the first steps @3Shoka?

**Comment by empeje** [comment]
Closed because of no activity.

**Pull request closed without merging**
