### PR TITLE
Application form and telegram link

### PR DESCRIPTION
**Pull request by hudakurniawan**
Updated the application form from Typeform to google form and updated the Telegram channel link.

### CODE REVIEW

**Comment by empeje** [comment]
Thank you for your contribution, but

https://kul.to/vInternForm21 can't be open by non Kulkul Gsuite members. Please check again ya.

**Comment by hudakurniawan** [comment]
Thanks for checking the link. I've changed the form permission.
However, the applicants have to signed in to a google account to fill the form since it is G-Suite behavior.

**Comment by empeje** [comment]
> Thanks for checking the link. I've changed the form permission.
> However, the applicants have to signed in to a google account to fill the form since it is G-Suite behavior.

In that case, we need to mention this on the markdown. Something saying that they need to have a Google account to fill the registration form.

**Comment by hudakurniawan** [comment]
I think they will intuitively know since the link will redirect to the Google Sign-in page if they have not signed in. The same as there is no mention as well in the other link such as discord, GitHub, etc.

**Comment by empeje** [comment]
> I think they will intuitively know since the link will redirect to the Google Sign-in page if they have not signed in. The same as there is no mention as well in the other link such as discord, GitHub, etc.

I think it is required since we need to tell them why it suddenly asks for Google Sign in, a typical form shouldn't ask for Google auth.

Discord and GitHub is a separate issue. Discord and GitHub are more like "Find us on GitHub, Find us on Discord, etc". If you read carefully we also onboard aspiring interns to things in GitHub such as what is "stars" in GitHub, also for the following crew in GitHub.

**Comment by hudakurniawan** [comment]
Sure, I have updated my commit

**Review by empeje — APPROVED** [review]

**Pull request merged**
