### PR TITLE
Add xianwei to the list of interns

### PR DESCRIPTION
**Pull request by Git-mind**
Preview URL is https://raw.githack.com/Git-mind/open-source/feature/add-xianwei/en_ID/#!index.md

### CODE REVIEW

**Comment by empeje** [comment]
Thank you for creating your first Pull Request to @kulkultech. In order to be accepted, you need to finish all the series of first steps. So I'll mark this PR as "pending-first-steps".

Here's my feedback for this PR, try to create a more creative bio for yourself 😄 

Perhaps adding image, LinkedIn profile, Instagram profile, or many others.

Screen Shot 2020-11-19 at 20 42 44

**Comment by galanggg** [comment]
raw githack com_Git-mind_open-source_feature_add-xianwei_en_ID_ (1)
Hi @Git-mind, your image is too big in this table

**Comment by empeje** [comment]
Hi, @Git-mind any issue with continuing the first steps?

**Comment by empeje** [comment]
Since I didn't receive any response from @Git-mind, I'll close this PR temporarily, you can reopen when you continue.

**Pull request closed without merging**
