### PR TITLE
Adding github logo to wiki homepage

### PR DESCRIPTION
**Pull request by cjj20**
Added the github logo and changed placement for fork on github text. Logo may need to be repositioned further as it is not centered.

Issue #156

### CODE REVIEW

**Comment by empeje** [comment]
Screenshot 2023-07-05 at 23 14 40
I think from my review in this [link](https://raw.githack.com/cjj20/open-source/feature/addgithublogo/en_ID/index.html#!pages/interns.md) the image is not well oriented and layout.

**Comment by cjj20** [comment]
I agree not too sure why the image appears that way. I'll look at the markdown again.  Issue #156

**Comment by cjj20** [comment]
Preview link: https://raw.githack.com/cjj20/open-source/feature/addgithublogo/en_ID/index.html#!index.md

**Comment by empeje** [comment]
so which one you propose this one or #164? I think those two PRs kinda duplicate.

**Comment by cjj20** [comment]
> so which one you propose this one or #164? I think those two PRs kinda duplicate.

#164  is better so I will go with that one. It uses gimmick so I think it's a better fit.

**Comment by cjj20** [comment]
> so which one you propose this one or #164? I think those two PRs kinda duplicate.

#164   is better so I will go with that one. It uses gimmick so I think it's a better fit.

**Pull request closed without merging**
