### PR TITLE
Claire to be added to the list of interns

### PR DESCRIPTION
**Pull request by cjj20**
Preview url is https://raw.githack.com/cjj20/open-source/feature/add-clairej/en_ID/index.html#!pages/interns.md

### CODE REVIEW

**Comment by empeje** [comment]
Thanks @cjj20 you'll be added once you finished the 1st step and pass our interview :)

To track your 1st step progress please refer to: https://open-source.kulkul.tech/en_ID/#!pages/progress.md

**Comment by cjj20** [comment]
Thank you and looking forward to it

**Comment by empeje** [comment]
One more PR togo for your next step @cjj20 

Screenshot 2023-07-31 at 21 45 35

**Comment by cjj20** [comment]
> One more PR togo for your next step @cjj20
> 
> Screenshot 2023-07-31 at 21 45 35

Looking forward to this :)

**Comment by empeje** [comment]
Well done @cjj20 !

**Pull request merged**
