### PR TITLE
Adding doc SSH in the FAQ for windows

### PR DESCRIPTION
**Pull request by HananAskarim**
Preview URL is https://raw.githack.com/HananAskarim/open-source/feature/add-SSH-in-FAQ/index.html

### CODE REVIEW

**Comment by empeje** [comment]
again, please commit using your email @HananAskarim

**Comment by HananAskarim** [comment]
Sorry, do I have to repeat the Pull Request again?

**Comment by empeje** [comment]
> Sorry, do I have to repeat the Pull Request again?

No need. You can use `git ammend`

**Comment by HananAskarim** [comment]
> > Sorry, do I have to repeat the Pull Request again?
> 
> No need. You can use `git ammend`

Thank you, I have done git amend

**Comment by empeje** [comment]
> > > Sorry, do I have to repeat the Pull Request again?
> > 
> > 
> > No need. You can use `git ammend`
> 
> Thank you, I have done git amend

Your email in this PR still the same

**Comment by HananAskarim** [comment]
I had done git amend

**Comment by empeje** [comment]
Screen Shot 2021-04-27 at 15 50 06
 
Still not using your email

**Pull request merged**
