### PR TITLE
Feature/separate steps

### PR DESCRIPTION
**Pull request by volkansahn**
[Issue 43](https://github.com/kulkultech/open-source/issues/43)
Separate Internship steps to improve traceability.  

Preview : https://raw.githack.com/volkansahn/open-source/feature/separate-steps/en_ID/#!index.md

### CODE REVIEW

**Review by empeje — CHANGES_REQUESTED** [review]
Hi @volkansahn, this is a good PR, however, the only thing I miss from the new setup compare to the existing page is the left sidebar pane where I can navigate to any step I want easily without clicking the top navigation menu.

**Comment by volkansahn** [comment]
Okay, you can ignore this PR then

**Comment by empeje** [comment]
> Okay, you can ignore this PR then

Hold on, are you interested to implement the sidebar manually? I think there's a possibility.

**Comment by volkansahn** [comment]
Actually, I have checked the script file to make sidebar move with scroll and stay at the end of the screen. But it is a bit complicated for me. 

You mean implement sidebar with markdown or using plain html. Also do you want to see a dynamic sidebar like current one?

**Comment by empeje** [comment]
> Actually, I have checked the script file to make sidebar move with scroll and stay at the end of the screen. But it is a bit complicated for me.
> 
> You mean implement sidebar with markdown or using plain html. Also do you want to see a dynamic sidebar like current one?

Either is fine, as long as we can navigate between steps easily without clicking the top menu.

**Comment by empeje** [comment]
Do you still want to work on this PR?

**Comment by volkansahn** [comment]
I think it is better to close this item for now.

**Pull request closed without merging**
