### PR TITLE
Fix question position in faq.md

### PR DESCRIPTION
**Pull request by aransafp**
There were 2 question about **virtual internship** in **references** section

image

Here is the URL preview : https://raw.githack.com/aransafp/open-source/feature/faq/index.html

### CODE REVIEW

**Comment by empeje** [comment]
Thank you for your PR @aransafp 

When making a pull request, we need to make sure we change as little as possible changes required to achieve the intended changes.

I think there's unnecessary changes like changing `*` to `-` which is not required and related to the proposal.

**Comment by aransafp** [comment]
Ahh, I see, thanks for the explanation. 

Then should i fix this ? close pull request ? or let it open pr ?

**Comment by empeje** [comment]
You can just update the PR as we use the **squash and merge** for our git-merge strategy.

**Comment by aransafp** [comment]
I'm already fix unnecessary changes. 

I just relized, changes ```*``` to ```-``` happens after I use "Format Document" for in VsCode. Other than fix the code structure, it also change that.

**Comment by empeje** [comment]
Looks good @aransafp, now the different is easy to check.

Overall looks good to me and I'll merge this.

**Pull request merged**
