### PR TITLE
Feature/contactuslink

### PR DESCRIPTION
**Pull request by cjj20**
Contact us link added to Kulkul OSS Wiki homepage.

### CODE REVIEW

**Comment by cjj20** [comment]
Please disregard commit e0bffe7.

**Comment by empeje** [comment]
Please add your preview URL @cjj20 :)

**Comment by cjj20** [comment]
Apologies again, Issue #157 , preview link: https://raw.githack.com/cjj20/open-source/feature/contactuslink/en_ID/index.html#!index.md

**Comment by empeje** [comment]
I think it will be better to link it to our discord link rather than the company's link because the company's link meant for different purpose.

**Comment by cjj20** [comment]
That makes sense, I'll update it.

**Comment by cjj20** [comment]
> I think it will be better to link it to our discord link rather than the company's link because the company's link meant for different purpose.

Contact link updated to discord link

**Comment by empeje** [comment]
Nicely done, thank you @cjj20

**Pull request merged**
