### PR TITLE
Improve references structure in FAQ page

### PR DESCRIPTION
**Pull request by aransafp**
Issue: [#131](https://github.com/kulkultech/open-source/issues/131)
Link for preview : https://raw.githack.com/aransafp/open-source/feature/faq-github-markdown/en_ID/#!pages/faq.md

image

### CODE REVIEW

**Comment by empeje** [comment]
There's too many commit and changes on the code, is it intentional? It is very hard for me to spot the different.

**Comment by aransafp** [comment]
My purpose to see the changes in raw-githack, that's why i make a lot of commits. Because the preview in markdownlivepreview is a little bit different from raw-githack. 

In the first half of commit mostly I did test to see what will happen in MidWiki, and for the last I fix some typos. I also made some mistake by creating a bad message commit. But basicly, at the end i only make the changes in references section. 

Do you have any advice about this ? should I make a new PR about this changes ?

thanks

**Comment by empeje** [comment]
Hi @aransafp I understand it now. I think after reviewing it again, I'll merge it and redesign it later.

Generally, each commit should be atomic. Learn more here: https://dev.to/paulinevos/atomic-commits-will-help-you-git-legit-35i7

But good job for the changes.

**Comment by aransafp** [comment]
Thanks for the reference, It's really helpful, sometimes i'm wondering how to write commit message or description when i fix and add feature at the same time. It also make review more easier.

**Pull request merged**
